### ISSUE TITLE
Icon does not get displayed on launcher

### ISSUE THREAD

**Issue by cao-** [jajasuperman/HexColorTime#8]
I saw you added an icon for the app.  But on my phone it does not get displayed under any launcher.  Instead, it gets displayed on F-Droid.  Is this an issue of my phone only?

**Comment by urtxintxa** [comment]
On mine and others the icon works perfectly.
I assume you have update the app, isn't it? What android version are you using?

**Comment by cao-** [comment]
Yes, I've updated the app (in fact now there is the "no text" option).  But the icon does not get displayed.  I tried to remove and reinstall it, but the problem persists.  Every other app icon instead works properly.  I'm on Android 6.0.1.

**Comment by urtxintxa** [comment]
I have test with some different devices, and I didn't see that problem.
What launchers did you test? Do you have any icon app?
It would be nice if you put logcat.

**Comment by cao-** [comment]
It just appeared that after clearing the cache data of the default launcher the icon started to display correctly.  So probably launchers were using the old cached icon.  The problem is not related to this app then.
