### ISSUE TITLE
F-Droid App's "Install" button gets disabled when HexColorTime is installed

### ISSUE THREAD

**Issue by michaelof** [jajasuperman/HexColorTime#9]
Hi, maybe you could take a look into this issue: https://gitlab.com/fdroid/fdroidclient/issues/857, as this issue is somehow (whyever) related to HexColorTime.

Thanks,
Michael

**Comment by urtxintxa** [comment]
As it said in that issue, I can't do anything. It is related with Android security [reasons](https://f-droid.org/wiki/page/FAQ_-_Client#I_can_download_apps.2C_but_then_.22Install.22_is_disabled._Why.3F) :S

I also tried installing HexColorTime with [Twilight ](https://play.google.com/store/apps/details?id=com.urbandroid.lux)app activated with no result.

So a solution is to disable this kind of apps.
Thanks for your report.
